[package]
name = "aoc_2022_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_01"
path = "/day_01/src/day_01.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
